### PR TITLE
Add underscore style: a_b_c_1_d.

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@jeremywohl what do you think?

**Comment by jeremywohl** [comment]
Thanks for the patch.  Out of curiosity, is there some system which uses such underscores (i.e. Rails or filesystems for paths, dots are common separators, ...), or is this an aesthetic preference?

**Comment by ruudk** [comment]
I use it to convert json blobs to database (redshift/postfris) column names. Those names cannot contain dots.

**Comment by jeremywohl** [comment]
Check "allow edits from maintainer"?

**Comment by jeremywohl** [comment]
@ruudk ^^^ re edits

**Comment by ruudk** [comment]
Thanks for fixing the stupid mistakes, I should've caught them 🙌😁

**Comment by jeremywohl** [comment]
No worries, I appreciate the submission.

**Pull request merged**
